//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long VariationOptionId { get; set; }
        public int Quantity { get; set; }
        public decimal PriceItem { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual VariationOption VariationOption { get; set; }
    }
}
