//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public decimal Discount { get; set; }
        public int Quantity { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Available { get; set; }
    }
}
